services:
  - type: web
    name: marketing-api
    env: python
    rootDir: marketing-API
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn luad_game_core.wsgi
    autoDeploy: true
