"""
Django settings for bbi_ecomm project.

Generated by 'django-admin startproject' using Django 3.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ
import google.auth
from django.utils.translation import gettext_lazy as _

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env_prod'))

DEBUG = True

# Attempt to load the Project ID into the environment, safely failing on error.
try:
    credentials, os.environ["GOOGLE_CLOUD_PROJECT"] = google.auth.default()
except google.auth.exceptions.DefaultCredentialsError:
    pass


SECRET_KEY = os.getenv("SECRET_KEY")

ALLOWED_HOSTS = [os.getenv("CLOUD_RUN_URL"), 'localhost', '.localhost', 'bamboobi.la', '.bamboobi.la']

# Application definition

SHARED_APPS = (
    'django_tenants',  # mandatory
    'tenant',  # you must list the app where your tenant model resides in

    'user',
    'product',
    'bbi_exchange',
    'rate',
    'common',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'parler',
    'djmoney',
    'djmoney.contrib.exchange',
    'sorl.thumbnail',
    'sorl_thumbnail_serializer',

    'django_cleanup.apps.CleanupConfig',

)

TENANT_APPS = [
    'user',
    'product',
    'rate',
    'common',

    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',

    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'parler',
    'djmoney',
    'djmoney.contrib.exchange',
    'sorl.thumbnail',
    'sorl_thumbnail_serializer',

    'django_cleanup.apps.CleanupConfig',
 
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_tenants.middleware.main.TenantMainMiddleware',

    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'bbi_ecomm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bbi_ecomm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Database
# Use django-environ to parse the connection string
DATABASES = {"default": env.db()}
DATABASES["default"]["ENGINE"] = 'django_tenants.postgresql_backend'

# If the flag as been set, configure to use proxy
if os.getenv("USE_CLOUD_SQL_AUTH_PROXY", None):
    DATABASES["default"]["HOST"] = "localhost"
    DATABASES["default"]["PORT"] = 5432

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")
# GS_DEFAULT_ACL = "publicRead"
DEFAULT_FILE_STORAGE = "common.storage.gcloud.GoogleCloudStorageAccessToken"
STATICFILES_STORAGE = "common.storage.gcloud.GoogleCloudStorageAccessToken"


STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TENANT_MODEL = "tenant.Tenant"

TENANT_DOMAIN_MODEL = "tenant.Domain"

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=600),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=600),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

LANGUAGES = [
   ('la', _('Lao')),
   ('en', _('English')),

]

PARLER_LANGUAGES = {
    None: (
        {'code': 'en',},
        {'code': 'la',},
    ),
    'default': {
        'fallbacks': ['en'],      
        'hide_untranslated': False,   # Default
    }
}
TRANSLATE_MIXIN = 'common.translate.mixings.TranslatedSerializerMixin'
TRANSLATE_FIELD = 'common.translate.field.DRFTranslatedFieldsField'

CURRENCIES = ('USD', 'LAK', 'THB')

EXCHANGE_BACKEND = 'bbi_exchange.backends.BBIBackend'

BBI_EXCHANGE_URL = "http://localhost:8000/api/v1/bbi_exchange/1"

BBI_EXCHANGE_KEY = ""

CURRENCY_MIXIN = 'common.currency.mixings.ConvertSerializerMixin'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

THUMBNAIL_FORCE_OVERWRITE = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
